title: Dopetrope
description: Dopetrope template for Jekyll
paginate: 10
baseUrl: /

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"